<a href="https://colab.research.google.com/github/Nareshnq/Pandas_Learning-/blob/main/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **Pandas DataFrame Creation Guide**

####  **Basic Rules for Creating DataFrames from Lists**

#### **Rule 1: Single List → Single Column**
- **Format:** `[value1, value2, value3]`
- **Result:** Creates a DataFrame with **1 column** and **multiple rows**
- **Structure:** Each value becomes a separate row in a single column

#### **Rule 2: Nested Lists → Multiple Columns**
- **Format:** `[[row1_data], [row2_data], [row3_data]]`
- **Result:** Creates a DataFrame with **multiple columns** and **multiple rows**
- **Structure:** Each inner list represents a row, and elements within become columns

---

####  **Default Index Behavior**

**Important:** If you don't explicitly define indices:
- **Row indices** default to: `0, 1, 2, ...`
- **Column indices** default to: `0, 1, 2, ...`

---

####  **Quick Reference Examples**

#### **Example 1:** Single List
```python
import pandas as pd
df = pd.DataFrame(['A', 'B', 'C'])
# Result: 3 rows × 1 column with indices 0,1,2

In [873]:
L = ['row1', 'row2', 'row3']
type(L)

list

In [874]:
import pandas as pd
L_ist = ['row1', 'row2', 'row3']

df = pd.DataFrame(L_ist, columns=["column1"])
df

column1
0    row1
1    row2
2    row3

In [875]:
# nested list
List2=[[1,3,4,5,56],[2,4.5,5,45]]
type(List2)

list

In [876]:
#with nested list
A=pd.DataFrame(List2) # note indexes and columns are not mentioned
A

0    1  2   3     4
0  1  3.0  4   5  56.0
1  2  4.5  5  45   NaN

In [877]:
# import pandas as pd
# A=pd.DataFrame([1,2.3,5] [1,3,4])  # error because no comma or no mention of data or indexes
# print(A)

### CUSTOM INDEXES AND COLUMNS

In [878]:
# 1st method
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=['A', 'B', 'C'],index=['row1', 'row2', 'row3'])
df

A  B  C
row1  1  2  3
row2  4  5  6
row3  7  8  9

In [879]:
# OR 2nd Method
columns = ['A', 'B', 'C']  # Valid variable name
index = ['row1', 'row2', 'row3']  # Valid variable name
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=columns, index=index) # make sure inside here these should be columns and index nothing else
df

A  B  C
row1  1  2  3
row2  4  5  6
row3  7  8  9

In [880]:
# PRACTICE

import pandas as pd

List=[[1,2,3],[4,6],[7,8,9]]
columns=['column1','column2','column3']
index= ['row1','row2','row3']
df1=pd.DataFrame(List,columns=columns,index=index)
df1

column1  column2  column3
row1        1        2      3.0
row2        4        6      NaN
row3        7        8      9.0

#### How do we check column names and index names of a data frame


In [881]:
# lets define dataframe first

df2=df1

In [882]:
# quick check

df2.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [883]:
# when we need a list as output

df2.columns.tolist()

['column1', 'column2', 'column3']

In [884]:
# When you want comprehensive information about the DataFrame

df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, row1 to row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  3 non-null      int64  
 1   column2  3 non-null      int64  
 2   column3  2 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 204.0+ bytes


In [885]:
# Same as df.columns (they're equivalent).

print(df2.keys())

Index(['column1', 'column2', 'column3'], dtype='object')


In [886]:
# when we need a list of indexes

df2.index.tolist()

['row1', 'row2', 'row3']

#### MAKING DATA FRAME USING A DICTIONARY


In [887]:
import pandas as pd
import numpy as np


dict_data= {"column1":[4,5,6,7,8],
            "column2":[4,5,6,7,8]}

dfA=pd.DataFrame(dict_data,columns=["colm1","colm2"],index=['row1','row2','row3','row4','row5'])
dfA  # ERROR

# the above code has errors
# 1. Dictionary keys become column names by default
# When you pass a dictionary to pd.DataFrame(), the keys automatically become column names:
# 2. The columns parameter has special behavior:
# If omitted: Uses dictionary keys as column names
# If provided: It selects/reorders columns from the dictionary
# If column names don't match dictionary keys: Creates those columns with NaN values

colm1 colm2
row1   NaN   NaN
row2   NaN   NaN
row3   NaN   NaN
row4   NaN   NaN
row5   NaN   NaN

### MAKING DATA FRAME USING A DICTIONARY


In [888]:
import pandas as pd
import numpy as np

dict_data= {"column1":[4,5,6,7,8],
            "column2":[4,8,6,10,8]}

dfAA=pd.DataFrame(dict_data,index=['row1','row2','row3','row4','row5'])  # hence no need to mention columns names here again
dfAA


column1  column2
row1        4        4
row2        5        8
row3        6        6
row4        7       10
row5        8        8

#### 📌TRANSPOSE PROPERTIES



In [889]:
import pandas as pd
# Lets Define the DataFrame A with  specific values


A = pd.DataFrame({
    'column1': [25, 56, 25, 89],
    'column2': [89, 84, 78, 52],
    'column3': [52, 84, 57, 96]
}, index=['row1', 'row2', 'row3', 'row4'])

A.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  4 non-null      int64
 1   column2  4 non-null      int64
 2   column3  4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes


In [890]:
# you can use the transpose() method or .T to switch the rows and columns.


transposed_A = A.T
transposed_A

row1  row2  row3  row4
column1    25    56    25    89
column2    89    84    78    52
column3    52    84    57    96

####  Finding Unique Values in Pandas

#### Pandas – Finding Unique Values

######   Mistakes we make thinkning it will be
`df.unique()` →  ERROR  
Reason: `unique()` works on **Series**, not **DataFrames**

####  Correct Usage
- Single column → `df['col'].unique()`
- Multiple columns → `df[['c1','c2']].apply(pd.unique)`
- Unique rows → `df.drop_duplicates()`
- Count unique → `df['col'].nunique()`

####  Rule
DataFrame = collection of Series → apply `unique()` column-wise



In [891]:
# lets take dataframe A for finding unique values
A

column1  column2  column3
row1       25       89       52
row2       56       84       84
row3       25       78       57
row4       89       52       96

In [892]:
# single column unique values ,let say column1
A['column1'].unique()

array([25, 56, 89])

In [893]:
# lets find unique values for column1 and column2
A[['column1','column2']].apply(pd.unique)

column1        [25, 56, 89]
column2    [89, 84, 78, 52]
dtype: object

In [894]:
# for three columns
A[['column1','column2','column3']].apply(pd.unique)

column1        [25, 56, 89]
column2    [89, 84, 78, 52]
column3    [52, 84, 57, 96]
dtype: object

In [895]:
# print all unique values from an entire dataframe

pd.unique(A.values.ravel())

# B.values: Converts the DataFrame to a NumPy array
# .ravel(): Flattens the array into a 1D array
# pd.unique(): Extracts unique values from the flattened array

array([25, 89, 52, 56, 84, 78, 57, 96])

In [896]:
#lets print A again

A

column1  column2  column3
row1       25       89       52
row2       56       84       84
row3       25       78       57
row4       89       52       96

In [897]:
# lets count the number of unique values in one column of dataframe A, lets say column1


A["column1"].nunique()

3

In [898]:
# lets count the number of unique values column wise in entire dataframe A


A.nunique()

column1    3
column2    4
column3    4
dtype: int64

In [899]:
 # Unique values across columns in each row


A.nunique(axis=1)

row1    3
row2    2
row3    3
row4    3
dtype: int64

In [900]:
# Sum of unique counts across all columns  # df.nunique().sum()


print("then total number of unique values in entire dataframe is :",A.nunique().sum())

then total number of unique values in entire dataframe is : 11


LOADING DATA

In [901]:
# some time we have to use raw strings to make it work , like df=pd.read_csv(r"copypathfile")

coffee=pd.read_csv("/content/drive/MyDrive/Python_Learning /Keith_Youtube_learning/Pandas_by_keith/coffee.csv")
coffee

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [902]:
# Uploading another file
import pandas as pd
bios=pd.read_csv('/content/drive/MyDrive/Python_Learning /Keith_Youtube_learning/Pandas_by_keith/bios.csv')
bios

athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux   
1                2         Arnaud Boetsch  1969-04-01           Meulan   
2                3           Jean Borotra  1898-08-13         Biarritz   
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe   
4                5           Albert Canet  1878-04-17       Wandsworth   
...            ...                    ...         ...              ...   
145495      149222      Polina Luchnikova  2002-01-30            Serov   
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)   
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas   
145498      149225         André Foussard  1899-05-19            Niort   
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill   

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN   
1                   Yvelines          FRA     France      183.0       76.0   
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0   
3                      Paris          FRA     France      168.0       64.0   
4                    England          GBR     France        NaN        NaN   
...                      ...          ...        ...        ...        ...   
145495            Sverdlovsk          RUS        ROC      167.0       61.0   
145496                Moskva          RUS        ROC      168.0       65.0   
145497           Arkhangelsk          RUS        ROC      163.0       55.0   
145498           Deux-Sèvres          FRA     France      166.0        NaN   
145499       New South Wales          AUS  Australia        NaN        NaN   

         died_date  
0       1960-10-02  
1              NaN  
2       1994-07-17  
3       1978-03-20  
4       1930-07-25  
...            ...  
145495         NaN  
145496         NaN  
145497         NaN  
145498  1986-03-18  
145499  2003-10-20  

[145500 rows x 10 columns]

#### ACCESSING DATA WITH PANDA


In [903]:
#coffee.head(9)
#coffee.tail(4)

coffee.sample(4, random_state=1)  #4 rows from the coffee and

#Setting a specific value (like 1) for random_state will give you the same random sample
# every time you run the code, as long as the DataFrame does not change.

Day Coffee Type  Units Sold
3   Tuesday       Latte          20
7  Thursday       Latte          30
6  Thursday    Espresso          40
2   Tuesday    Espresso          30

####📍 ACCESSING SPECIFIC DATA VALUES FROM DATAFRAME
There are two ways of doing it


1.iloc

2.loc


.

.
####  1.>> `.iloc[]` (Integer Location)
**Purpose:** Access data by INTEGER POSITION (row/column index numbers)

##### Key Features:
- **Integer-based** indexing (0, 1, 2, ...)
- **Exclusive** of end range (like Python slicing)
- **Doesn't use** actual index/column names
- **Faster** than `loc` for large datasets

##### Syntax:
```python
df.iloc[row_index, column_index]

In [904]:
# PLEASE CHECK THE DIFFERENCE BETWEEN iloc and loc as I was confused between index style counting between them


In [905]:
coffee

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [906]:
# Single cell
coffee.iloc[0, 1]           # Row 0, Column 1

'Espresso'

In [907]:
# Row slice
coffee.iloc[2:5, :]         # Rows 2 to 4, all columns

Day Coffee Type  Units Sold
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [908]:
coffee

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [909]:
# Column slice
coffee.iloc[:, 1:3]         # All rows, columns 1 to 2


Coffee Type  Units Sold
0     Espresso          25
1        Latte          15
2     Espresso          30
3        Latte          20
4     Espresso          35
5        Latte          25
6     Espresso          40
7        Latte          30
8     Espresso          45
9        Latte          35
10    Espresso          45
11       Latte          35
12    Espresso          45
13       Latte          35

In [910]:
# Specific rows & columns
coffee.iloc[[0, 2, 3], [1, 2]]  # Rows 0,2,3 and columns 1,2

Coffee Type  Units Sold
0    Espresso          25
2    Espresso          30
3       Latte          20

In [911]:
# Single row
coffee.iloc[3]              # Row 3 (all columns)

Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object

In [912]:
# Single column
coffee.iloc[:, 2]           # All rows, column 2

0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

## 📍 2. >>  `.loc[ ]` (Label Location)

| Aspect | Description |
|------|------------|
| Purpose | Access data by **LABEL / NAME** (row index & column names) |
| Key Feature | Label-based indexing (uses actual names) |
| Range Behavior | **Inclusive** of end range |
| Indexing Uses | Uses **index labels** & **column names** |
| Readability | More readable when you know labels |


📍 `.loc` vs `.iloc` (Quick Notes)

#### `.iloc[ ]` — Position-based
- Uses **integer positions**
- `0` = first row, `1` = second row
- **End NOT included** (like slicing / `range()`)

Example:
`df.iloc[0:3]` → rows at positions `0,1,2`

---

###### `.loc[ ]` — Label-based
- Uses **index labels / names**
- Labels can be numbers, but they are **not positions**
- **End IS included**

Example:
`df.loc[0:3]` → rows with labels `0,1,2,3`

---

###### 🧠 Memory Trick
- **iloc** → integer position (Python-style)
- **loc** → label / name-based


In [913]:
coffee

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [914]:
# Single cell
coffee.loc[0,'Coffee Type']

'Espresso'

In [915]:
# Row slice (inclusive!)
coffee.loc['1':'3', :]    # Rows row1 THROUGH row3 , usually row should have some name but here are integers that is why it was confusing earlier for counting

Day Coffee Type  Units Sold
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [916]:
# Column slice
coffee.loc[:, 'Day':'Units Sold']     # Columns colmn1 THROUGH column3

Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

### More function to find specific values from the data frame 1- (.iat)  2- (.at )
**`.at` and `.iat`:**

* These methods are optimized for accessing or modifying a **single value** in a pandas DataFrame.
* **`.at`** is **label-based**, meaning it uses row and column labels to locate the value.
* **`.iat`** is **integer-based**, meaning it uses row and column integer indices.
* They are **faster and more efficient** for single value operations compared to `.loc` and `.iloc`.

**`.loc` and `.iloc`:**
* While they can access single values, they are **slower** than `.at` and `.iat` for such tasks because they are designed to handle complex operations like slicing and filtering.

In [917]:
#print coffee day from dataframe coffee

coffee['Day']



0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [918]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [919]:
#lets print Units Sold Column


coffee["Units Sold"] # no error

# coffee.Units Sold  >>> This  will throw an error because of space (SyntaxError: invalid syntax)

0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

## Sorting the Data (ascending or descending)


| Topic | Details |
|------|--------|
| Method | `.sort_values('column_name')` |

| Purpose | Sort DataFrame by a specified column |

| Ascending Order | `df.sort_values('column_name')` |

| Descending Order | `df.sort_values('column_name', ascending=False)` |


In [920]:
#single column sorting

# lets check the column units sold in  ascending order
coffee.sort_values("Units Sold") # by default it is ascending order

Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [921]:
# lets check the column units sold in  descending order
coffee.sort_values("Units Sold",ascending = False)

Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [922]:
#multiple column sorting
coffee.sort_values(["Coffee Type","Units Sold"]) # again the default sort order is ascending order

Day Coffee Type  Units Sold
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35

In [923]:
#multiple column sorting but in specific order
coffee.sort_values(["Coffee Type","Units Sold"],ascending=[0,1])


# Key Rule
# When sorting by multiple columns, ascending must be a list
# Each value in the list corresponds position-by-position to the columns
# 0 = ascending False = descending order
# 1 = ascending True =  ascending order
# (Python treats 0/1 as False/True)
# Hence >> # Units Sold	0 (False)	Descending (high → low) AND  Coffee Type	1 (True)	Ascending (A → Z)

Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

### FILTERING THE DATA



In [924]:
 bios.head(5)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17  
3                 Paris          FRA  France      168.0       64.0  1978-03-20  
4               England          GBR  France        NaN        NaN  1930-07-25

In [925]:
bios.columns.tolist()

['athlete_id',
 'name',
 'born_date',
 'born_city',
 'born_region',
 'born_country',
 'NOC',
 'height_cm',
 'weight_kg',
 'died_date']

In [926]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   athlete_id    145500 non-null  int64  
 1   name          145500 non-null  object 
 2   born_date     143693 non-null  object 
 3   born_city     110908 non-null  object 
 4   born_region   110908 non-null  object 
 5   born_country  110908 non-null  object 
 6   NOC           145499 non-null  object 
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object 
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB


In [927]:
# Can you  sort them by height and weight , both in descending order ??


bios.sort_values(['height_cm','weight_kg'],ascending=False)

athlete_id                   name   born_date           born_city  \
89070        89782               Yao Ming  1980-09-12      Xuhui District   
6978          7013        Arvydas Sabonis  1964-12-19              Kaunas   
5781          5804         Tommy Burleson  1952-02-24           Crossnore   
89075        89787         Roberto Dueñas  1975-11-01              Madrid   
5673          5696         Gunther Behnke  1963-01-19          Leverkusen   
...            ...                    ...         ...                 ...   
145490      149217            Sin Ye-Chan  1995-06-13                 NaN   
145491      149218          Matthew Wepke  1989-12-05                 NaN   
145492      149219  Carlos García-Ordóñez  1927-04-24  La Habana (Havana)   
145493      149220     Landysh Falyakhova  1998-08-31    Dva Polya Artash   
145499      149814          Bill Phillips  1913-07-15        Dulwich Hill   

                 born_region born_country                         NOC  \
89070               Shanghai          CHN  People's Republic of China   
6978                  Kaunas          LTU      Lithuania Soviet Union   
5781          North Carolina          USA               United States   
89075                 Madrid          ESP                       Spain   
5673     Nordrhein-Westfalen          GER                     Germany   
...                      ...          ...                         ...   
145490                   NaN          NaN           Republic of Korea   
145491                   NaN          NaN                     Jamaica   
145492   Ciudad de La Habana          CUB                        Cuba   
145493  Respublika Tatarstan          RUS                         ROC   
145499       New South Wales          AUS                   Australia   

        height_cm  weight_kg   died_date  
89070       226.0      141.0         NaN  
6978        223.0      122.0         NaN  
5781        223.0      102.0         NaN  
89075       221.0      137.0         NaN  
5673        221.0      114.0         NaN  
...           ...        ...         ...  
145490        NaN        NaN         NaN  
145491        NaN        NaN         NaN  
145492        NaN        NaN  2019-11-24  
145493        NaN        NaN         NaN  
145499        NaN        NaN  2003-10-20  

[145500 rows x 10 columns]

In [928]:
#  lets find players who are taller than 215 cms


tall_athlete= bios[bios['height_cm']>215]
tall_athlete

athlete_id                   name   born_date               born_city  \
5089          5108     Viktor Pankrashkin  1957-06-19         Moskva (Moscow)   
5583          5606   Paulinho Villas Boas  1963-01-26               São Paulo   
5673          5696         Gunther Behnke  1963-01-19              Leverkusen   
5716          5739               Uwe Blab  1962-03-26        München (Munich)   
5781          5804         Tommy Burleson  1952-02-24               Crossnore   
5796          5819          Andy Campbell  1956-07-21               Melbourne   
6223          6250            Lars Hansen  1954-09-27  København (Copenhagen)   
6270          6298            Hu Zhangbao  1963-04-05                     NaN   
6409          6440       Sergey Kovalenko  1947-08-11                     NaN   
6420          6451          Jānis Krūmiņš  1930-01-30                   Cēsis   
6504          6537            Luc Longley  1969-01-19               Melbourne   
6722          6755       Shaquille O'Neal  1972-03-06                  Newark   
6937          6972         David Robinson  1965-08-06                Key West   
6978          7013        Arvydas Sabonis  1964-12-19                  Kaunas   
7074          7111         Paulo da Silva  1963-07-21               São Paulo   
7188          7226     Vladimir Tkachenko  1957-09-20               Golovinka   
7281          7320       Stojko Vranković  1964-01-22                   Drniš   
7376          7416    Eurelijus Žukauskas  1973-08-22                Klaipėda   
52608        52983        Aleksey Kazakov  1976-03-18      Naberezhnye Chelny   
82100        82753          Frédéric Weis  1977-06-22              Thionville   
89070        89782               Yao Ming  1980-09-12          Xuhui District   
89075        89787         Roberto Dueñas  1975-11-01                  Madrid   
107408      108533       Peter John Ramos  1985-05-23                 Fajardo   
112312      113568           Stanko Barać  1986-08-13                  Mostar   
112332      113588    Andreas Glyniadakis  1981-08-26                  Chania   
112337      113593          Hamed Haddadi  1985-05-19                   Ahvaz   
118663      120400         Timofey Mozgov  1986-07-16                     NaN   
118676      120415        Dmitry Musersky  1988-10-29                Makiïvka   
120266      122147           Zhang Zhaoxu  1987-11-18                 Binzhou   
121694      123709            Salah Mejri  1986-06-15                Jendouba   
123850      126093         Tyson Chandler  1982-10-02                 Hanford   
130460      133147               Li Muhao  1992-06-02                 Guiyang   
130461      133148                Zhou Qi  1996-01-16                Xinxiang   
138671      142084          Ondřej Balvín  1992-09-20          Ústí nad Labem   
139365      142836         Moustapha Fall  1992-02-23                   Paris   

                            born_region born_country  \
5089                             Moskva          RUS   
5583                          São Paulo          BRA   
5673                Nordrhein-Westfalen          GER   
5716                             Bayern          GER   
5781                     North Carolina          USA   
5796                           Victoria          AUS   
6223                        Hovedstaden          DEN   
6270                                NaN          NaN   
6409                                NaN          NaN   
6420                        Cēsu novads          LAT   
6504                           Victoria          AUS   
6722                         New Jersey          USA   
6937                            Florida          USA   
6978                             Kaunas          LTU   
7074                          São Paulo          BRA   
7188                     Krasnodar Kray          RUS   
7281          Šibensko-kninska županija          CRO   
7376                           Klaipėda          LTU   
52608              Respubli

In [929]:
# Filter athletes weighing more than 80 kg


athlete_80plus=bios[bios['weight_kg']>80]
athlete_80plus

athlete_id               name   born_date           born_city  \
47              48         Sara Gomer  1964-05-13             Torquay   
74              75       Simon Archer  1973-06-27      Leamington Spa   
79              80         Neil Broad  1966-11-20           Cape Town   
95              96         Andy Goode  1960-01-30  Welwyn Garden City   
100            101         Chris Hunt  1968-12-01              Bolton   
...            ...                ...         ...                 ...   
145464      149191    Joonas Nättinen  1991-01-03               Jämsä   
145465      149192  Stanislav Galiyev  1992-01-17     Moskva (Moscow)   
145466      149193     Mikkel Aagaard  1995-10-18       Frederikshavn   
145468      149195  Justin Abdelkader  1987-02-25            Muskegon   
145473      149200     Toms Andersons  1993-11-25                Rīga   

         born_region born_country            NOC  height_cm  weight_kg  \
47           England          GBR  Great Britain      190.0       85.0   
74           England          GBR  Great Britain      189.0       86.0   
79      Western Cape          RSA  Great Britain      191.0       87.0   
95           England          GBR  Great Britain      183.0       83.0   
100          England          GBR  Great Britain      182.0       88.0   
...              ...          ...            ...        ...        ...   
145464   Keski-Suomi          FIN        Finland      189.0       90.0   
145465        Moskva          RUS            ROC      188.0       82.0   
145466   Nordjylland          DEN        Denmark      184.0       81.0   
145468      Michigan          USA  United States      187.0       97.0   
145473          Rīga          LAT         Latvia      185.0       86.0   

       died_date  
47           NaN  
74           NaN  
79           NaN  
95           NaN  
100          NaN  
...          ...  
145464       NaN  
145465       NaN  
145466       NaN  
145468       NaN  
145473       NaN  

[24715 rows x 10 columns]

In [930]:
# Filter athletes between 170-180 cm tall


tall_athlete= bios[(bios['height_cm']>=170)&(bios['height_cm']<=180)] # bios[()&()]
tall_athlete

athlete_id                  name   born_date         born_city  \
6                7         Patrick Chila  1969-11-27       Ris-Orangis   
17              18  Jean-Philippe Gatien  1968-10-16              Alès   
26              27     Christophe Legoût  1973-08-06       Montbéliard   
31              32       Guillaume Raoux  1970-02-14  Bagnols-sur-Cèze   
32              33      Stéphane Renault  1968-03-01          Barfleur   
...            ...                   ...         ...               ...   
145244      148963          Matej Baloga  1997-08-08            Prešov   
145246      148965          Ján Koristek  1996-07-11            Zvolen   
145248      148967            Marko Daňo  1994-11-30        Eisenstadt   
145252      148972         Libor Hudáček  1990-09-07            Levoča   
145460      149187         Nauris Sējējs  2001-03-15              Rīga   

            born_region born_country       NOC  height_cm  weight_kg died_date  
6               Essonne          FRA    France      180.0       73.0       NaN  
17                 Gard          FRA    France      178.0       73.0       NaN  
26                Doubs          FRA    France      177.0       75.0       NaN  
31                 Gard          FRA    France      180.0       77.0       NaN  
32               Manche          FRA    France      180.0       72.0       NaN  
...                 ...          ...       ...        ...        ...       ...  
145244           Prešov          SVK  Slovakia      175.0       69.0       NaN  
145246  Banská Bystrica          SVK  Slovakia      178.0       75.0       NaN  
145248       Burgenland          AUT  Slovakia      180.0       83.0       NaN  
145252           Prešov          SVK  Slovakia      175.0       78.0       NaN  
145460             Rīga          LAT    Latvia      180.0       84.0       NaN  

[44641 rows x 10 columns]

In [931]:
# Filter athletes weighing 70-80 kg


medium_weight_athlete= bios[(bios['weight_kg']>=70)&(bios['weight_kg']<=80)] # bios[()&()]
medium_weight_athlete

athlete_id               name   born_date    born_city  \
1                2     Arnaud Boetsch  1969-04-01       Meulan   
2                3       Jean Borotra  1898-08-13     Biarritz   
5                6  Nicolas Chatelain  1970-01-13       Amiens   
6                7      Patrick Chila  1969-11-27  Ris-Orangis   
16              17         Guy Forget  1965-01-04   Casablanca   
...            ...                ...         ...          ...   
145057      148769     Eduard Latypov  1994-03-21       Hrodna   
145245      148964    Tomáš Sklenárik  1999-10-13       Revúca   
145246      148965       Ján Koristek  1996-07-11       Zvolen   
145252      148972      Libor Hudáček  1990-09-07       Levoča   
145461      149188       Kent Johnson  2002-10-18   Port Moody   

                 born_region born_country       NOC  height_cm  weight_kg  \
1                   Yvelines          FRA    France      183.0       76.0   
2       Pyrénées-Atlantiques          FRA    France      183.0       76.0   
5                      Somme          FRA    France      181.0       70.0   
6                    Essonne          FRA    France      180.0       73.0   
16         Casablanca-Settat          MAR    France      189.0       79.0   
...                      ...          ...       ...        ...        ...   
145057                Hrodna          BLR       ROC      176.0       71.0   
145245       Banská Bystrica          SVK  Slovakia      185.0       75.0   
145246       Banská Bystrica          SVK  Slovakia      178.0       75.0   
145252                Prešov          SVK  Slovakia      175.0       78.0   
145461      British Columbia          CAN    Canada      185.0       75.0   

         died_date  
1              NaN  
2       1994-07-17  
5              NaN  
6              NaN  
16             NaN  
...            ...  
145057         NaN  
145245         NaN  
145246         NaN  
145252         NaN  
145461         NaN  

[30892 rows x 10 columns]

In [932]:
# filtering multiple columns
# Filter tall athlete >215cm AND medium_weight_athlete>80kg


tall_and_medium_weight_athelet=bios[(bios['height_cm']>=215) & (bios['weight_kg']>=80)]
tall_and_medium_weight_athelet

athlete_id                   name   born_date               born_city  \
5089          5108     Viktor Pankrashkin  1957-06-19         Moskva (Moscow)   
5583          5606   Paulinho Villas Boas  1963-01-26               São Paulo   
5599          5622      Vladimir Andreyev  1945-06-14               Astrakhan   
5673          5696         Gunther Behnke  1963-01-19              Leverkusen   
5716          5739               Uwe Blab  1962-03-26        München (Munich)   
5781          5804         Tommy Burleson  1952-02-24               Crossnore   
5796          5819          Andy Campbell  1956-07-21               Melbourne   
6223          6250            Lars Hansen  1954-09-27  København (Copenhagen)   
6270          6298            Hu Zhangbao  1963-04-05                     NaN   
6409          6440       Sergey Kovalenko  1947-08-11                     NaN   
6420          6451          Jānis Krūmiņš  1930-01-30                   Cēsis   
6504          6537            Luc Longley  1969-01-19               Melbourne   
6722          6755       Shaquille O'Neal  1972-03-06                  Newark   
6937          6972         David Robinson  1965-08-06                Key West   
6978          7013        Arvydas Sabonis  1964-12-19                  Kaunas   
7056          7093               Shan Tao  1970-05-30                Tangshan   
7074          7111         Paulo da Silva  1963-07-21               São Paulo   
7188          7226     Vladimir Tkachenko  1957-09-20               Golovinka   
7281          7320       Stojko Vranković  1964-01-22                   Drniš   
7298          7337            Wang Zhizhi  1977-07-08                 Beijing   
7376          7416    Eurelijus Žukauskas  1973-08-22                Klaipėda   
52520        52894           Marcin Nowak  1975-10-17             Częstochowa   
52604        52979     Stanislav Dineykin  1973-10-10              Blagodarny   
52608        52983        Aleksey Kazakov  1976-03-18      Naberezhnye Chelny   
82100        82753          Frédéric Weis  1977-06-22              Thionville   
82105        82758           Gregor Fucka  1971-08-07                   Kranj   
89070        89782               Yao Ming  1980-09-12          Xuhui District   
89075        89787         Roberto Dueñas  1975-11-01                  Madrid   
107369      108494              Pau Gasol  1980-07-06               Barcelona   
107408      108533       Peter John Ramos  1985-05-23                 Fajardo   
112312      113568           Stanko Barać  1986-08-13                  Mostar   
112327      113583      Patrick Femerling  1975-03-04                 Hamburg   
112330      113586      Ioannis Bourousis  1983-11-17                Karditsa   
112332      113588    Andreas Glyniadakis  1981-08-26                  Chania   
112337      113593          Hamed Haddadi  1985-05-19                   Ahvaz   
112358      113614     Aleksey Savrasenko  1979-02-28               Krasnodar   
118663      120400         Timofey Mozgov  1986-07-16                     NaN   
118676      120415        Dmitry Musersky  1988-10-29                Makiïvka   
120266      122147           Zhang Zhaoxu  1987-11-18                 Binzhou   
121694      123709            Salah Mejri  1986-06-15                Jendouba   
123850      126093         Tyson Chandler  1982-10-02                 Hanford   
130460      133147               Li Muhao  1992-06-02                 Guiyang   
130461      133148                Zhou Qi  1996-01-16                Xinxiang   
131058      133820            Rudy Gobert  1992-06-26           Saint-Quentin   
138671      142084          Ondřej Balvín  1992-09-20          Ústí nad Labem   
141018      144554          Yuta Watanabe  1994-10-13         Ayauta district   

                            born_region born_country  \
5089                             Moskva          RUS   
5583                          São Paulo          BRA   
5599                          As

In [933]:
tall_and_medium_weight_athelet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, 5089 to 141018
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   athlete_id    46 non-null     int64  
 1   name          46 non-null     object 
 2   born_date     46 non-null     object 
 3   born_city     43 non-null     object 
 4   born_region   43 non-null     object 
 5   born_country  43 non-null     object 
 6   NOC           46 non-null     object 
 7   height_cm     46 non-null     float64
 8   weight_kg     46 non-null     float64
 9   died_date     3 non-null      object 
dtypes: float64(2), int64(1), object(7)
memory usage: 5.0+ KB


In [934]:
# player who has height more than 215cm and born in USA


playersX = bios[(bios['height_cm']>215)  & (bios['born_country']=='USA')]
playersX

athlete_id              name   born_date  born_city     born_region  \
5781          5804    Tommy Burleson  1952-02-24  Crossnore  North Carolina   
6722          6755  Shaquille O'Neal  1972-03-06     Newark      New Jersey   
6937          6972    David Robinson  1965-08-06   Key West         Florida   
123850      126093    Tyson Chandler  1982-10-02    Hanford      California   

       born_country            NOC  height_cm  weight_kg died_date  
5781            USA  United States      223.0      102.0       NaN  
6722            USA  United States      216.0      137.0       NaN  
6937            USA  United States      216.0      107.0       NaN  
123850          USA  United States      216.0      107.0       NaN

In [935]:
playersX.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 5781 to 123850
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   athlete_id    4 non-null      int64  
 1   name          4 non-null      object 
 2   born_date     4 non-null      object 
 3   born_city     4 non-null      object 
 4   born_region   4 non-null      object 
 5   born_country  4 non-null      object 
 6   NOC           4 non-null      object 
 7   height_cm     4 non-null      float64
 8   weight_kg     4 non-null      float64
 9   died_date     0 non-null      object 
dtypes: float64(2), int64(1), object(7)
memory usage: 524.0+ bytes


In [936]:
# find player names starts with Keith


players_K=bios[bios['name'].str.contains('Keith')]
players_K


# Case-SENSITIVE matching
# Will only find: 'Keith', 'Keith Moon', 'Keith Richards'
# Will NOT find: 'keith', 'KEITH', 'KeItH'

athlete_id                  name   born_date         born_city  \
1897          1907          Keith Hanlon  1966-09-01               NaN   
3505          3517         Keith Wallace  1961-03-29           Preston   
6228          6255         Keith Hartley  1940-10-15         Vancouver   
8898          8946           Keith Mwila  1966-01-01               NaN   
12053        12118          Keith Hervey  1898-11-03            Fulham   
...            ...                   ...         ...               ...   
109900      111105     Keith Cumberpatch  1927-08-25      Christchurch   
115973      117348       Keith Sanderson  1975-02-02          Plymouth   
117676      119195          Duncan Keith  1983-07-16          Winnipeg   
122121      124176        Keith Ferguson  1979-09-07              Sale   
127310      129749  Tracy Keith-Matchitt  1990-03-30  Palmerston North   

              born_region born_country            NOC  height_cm  weight_kg  \
1897                  NaN          NaN        Ireland        NaN        NaN   
3505              England          GBR  Great Britain      165.0       51.0   
6228     British Columbia          CAN         Canada      200.0       85.0   
8898                  NaN          NaN         Zambia        NaN        NaN   
12053             England          GBR  Great Britain        NaN        NaN   
...                   ...          ...            ...        ...        ...   
109900         Canterbury          NZL    New Zealand        NaN        NaN   
115973      Massachusetts          USA  United States      183.0       95.0   
117676           Manitoba          CAN         Canada      185.0       88.0   
122121           Victoria          AUS      Australia      176.0       78.0   
127310  Manawatu-Wanganui          NZL   Cook Islands      167.0       60.0   

         died_date  
1897           NaN  
3505    1999-12-31  
6228           NaN  
8898    1993-01-09  
12053   1973-02-22  
...            ...  
109900  2013-11-15  
115973         NaN  
117676         NaN  
122121         NaN  
127310         NaN  

[70 rows x 10 columns]

In [937]:
players_K.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 1897 to 127310
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   athlete_id    70 non-null     int64  
 1   name          70 non-null     object 
 2   born_date     70 non-null     object 
 3   born_city     59 non-null     object 
 4   born_region   59 non-null     object 
 5   born_country  59 non-null     object 
 6   NOC           70 non-null     object 
 7   height_cm     50 non-null     float64
 8   weight_kg     50 non-null     float64
 9   died_date     26 non-null     object 
dtypes: float64(2), int64(1), object(7)
memory usage: 8.1+ KB


In [938]:
# find player names starts with Keith,'Keith', 'keith', 'KEITH', 'KeItH'


bios[bios['name'].str.contains('Keith',case=False)]


# #  case=False - ignores uppercase/lowercase
# Will find ALL these: 'Keith', 'keith', 'KEITH', 'KeItH'

athlete_id                  name   born_date         born_city  \
1897          1907          Keith Hanlon  1966-09-01               NaN   
3505          3517         Keith Wallace  1961-03-29           Preston   
6228          6255         Keith Hartley  1940-10-15         Vancouver   
8898          8946           Keith Mwila  1966-01-01               NaN   
12053        12118          Keith Hervey  1898-11-03            Fulham   
...            ...                   ...         ...               ...   
109900      111105     Keith Cumberpatch  1927-08-25      Christchurch   
115973      117348       Keith Sanderson  1975-02-02          Plymouth   
117676      119195          Duncan Keith  1983-07-16          Winnipeg   
122121      124176        Keith Ferguson  1979-09-07              Sale   
127310      129749  Tracy Keith-Matchitt  1990-03-30  Palmerston North   

              born_region born_country            NOC  height_cm  weight_kg  \
1897                  NaN          NaN        Ireland        NaN        NaN   
3505              England          GBR  Great Britain      165.0       51.0   
6228     British Columbia          CAN         Canada      200.0       85.0   
8898                  NaN          NaN         Zambia        NaN        NaN   
12053             England          GBR  Great Britain        NaN        NaN   
...                   ...          ...            ...        ...        ...   
109900         Canterbury          NZL    New Zealand        NaN        NaN   
115973      Massachusetts          USA  United States      183.0       95.0   
117676           Manitoba          CAN         Canada      185.0       88.0   
122121           Victoria          AUS      Australia      176.0       78.0   
127310  Manawatu-Wanganui          NZL   Cook Islands      167.0       60.0   

         died_date  
1897           NaN  
3505    1999-12-31  
6228           NaN  
8898    1993-01-09  
12053   1973-02-22  
...            ...  
109900  2013-11-15  
115973         NaN  
117676         NaN  
122121         NaN  
127310         NaN  

[70 rows x 10 columns]

In [939]:
bios[bios['name'].str.contains('Keith|patrick',case=False)] #| works like 'Or'

athlete_id               name   born_date              born_city  \
6                7      Patrick Chila  1969-11-27            Ris-Orangis   
119            120   Patrick Wheatley  1899-01-20                Vryheid   
319            320  Patrick De Koning  1961-04-23            Dendermonde   
1897          1907       Keith Hanlon  1966-09-01                    NaN   
2115          2125       Patrick Jopp  1962-01-08                    NaN   
...            ...                ...         ...                    ...   
143975      147633  Patrick Chinyemba  2001-01-03                    NaN   
144172      147850      Patrick Jakob  1996-10-17  Sankt Johann in Tirol   
144547      148239  Patrick Galbraith  1986-03-11              Haderslev   
144565      148257    Patrick Russell  1993-01-04               Gentofte   
145435      149158  Patrick Gasienica  1998-11-28                McHenry   

            born_region born_country            NOC  height_cm  weight_kg  \
6               Essonne          FRA         France      180.0       73.0   
119       KwaZulu-Natal          RSA  Great Britain        NaN        NaN   
319     Oost-Vlaanderen          BEL        Belgium      178.0       92.0   
1897                NaN          NaN        Ireland        NaN        NaN   
2115                NaN          NaN    Switzerland      176.0       67.0   
...                 ...          ...            ...        ...        ...   
143975              NaN          NaN         Zambia        NaN        NaN   
144172            Tirol          AUT        Austria        NaN        NaN   
144547       Syddanmark          DEN        Denmark        NaN        NaN   
144565      Hovedstaden          DEN        Denmark      186.0       93.0   
145435         Illinois          USA  United States        NaN        NaN   

         died_date  
6              NaN  
119     1967-11-05  
319            NaN  
1897           NaN  
2115           NaN  
...            ...  
143975         NaN  
144172         NaN  
144547         NaN  
144565         NaN  
145435  2023-06-12  

[303 rows x 10 columns]

In [940]:
# print all rows from the bios DataFrame where the 'name' column contains either
# "Keith" OR "patrick" (case-insensitive).



bios[bios['name'].str.contains('Keith|patrick', case=False)]


#    str.contains() searches for text patterns
#    'Keith|patrick' - the | means OR
#     case=False - ignores uppercase/lowercase

athlete_id               name   born_date              born_city  \
6                7      Patrick Chila  1969-11-27            Ris-Orangis   
119            120   Patrick Wheatley  1899-01-20                Vryheid   
319            320  Patrick De Koning  1961-04-23            Dendermonde   
1897          1907       Keith Hanlon  1966-09-01                    NaN   
2115          2125       Patrick Jopp  1962-01-08                    NaN   
...            ...                ...         ...                    ...   
143975      147633  Patrick Chinyemba  2001-01-03                    NaN   
144172      147850      Patrick Jakob  1996-10-17  Sankt Johann in Tirol   
144547      148239  Patrick Galbraith  1986-03-11              Haderslev   
144565      148257    Patrick Russell  1993-01-04               Gentofte   
145435      149158  Patrick Gasienica  1998-11-28                McHenry   

            born_region born_country            NOC  height_cm  weight_kg  \
6               Essonne          FRA         France      180.0       73.0   
119       KwaZulu-Natal          RSA  Great Britain        NaN        NaN   
319     Oost-Vlaanderen          BEL        Belgium      178.0       92.0   
1897                NaN          NaN        Ireland        NaN        NaN   
2115                NaN          NaN    Switzerland      176.0       67.0   
...                 ...          ...            ...        ...        ...   
143975              NaN          NaN         Zambia        NaN        NaN   
144172            Tirol          AUT        Austria        NaN        NaN   
144547       Syddanmark          DEN        Denmark        NaN        NaN   
144565      Hovedstaden          DEN        Denmark      186.0       93.0   
145435         Illinois          USA  United States        NaN        NaN   

         died_date  
6              NaN  
119     1967-11-05  
319            NaN  
1897           NaN  
2115           NaN  
...            ...  
143975         NaN  
144172         NaN  
144547         NaN  
144565         NaN  
145435  2023-06-12  

[303 rows x 10 columns]

In [941]:
# Or explicitly
bios[bios['name'].str.contains('Keith|patrick', case=False, regex=True)] #  regex=True is always default , we dont need to write it if it is true,more explanation is below

athlete_id               name   born_date              born_city  \
6                7      Patrick Chila  1969-11-27            Ris-Orangis   
119            120   Patrick Wheatley  1899-01-20                Vryheid   
319            320  Patrick De Koning  1961-04-23            Dendermonde   
1897          1907       Keith Hanlon  1966-09-01                    NaN   
2115          2125       Patrick Jopp  1962-01-08                    NaN   
...            ...                ...         ...                    ...   
143975      147633  Patrick Chinyemba  2001-01-03                    NaN   
144172      147850      Patrick Jakob  1996-10-17  Sankt Johann in Tirol   
144547      148239  Patrick Galbraith  1986-03-11              Haderslev   
144565      148257    Patrick Russell  1993-01-04               Gentofte   
145435      149158  Patrick Gasienica  1998-11-28                McHenry   

            born_region born_country            NOC  height_cm  weight_kg  \
6               Essonne          FRA         France      180.0       73.0   
119       KwaZulu-Natal          RSA  Great Britain        NaN        NaN   
319     Oost-Vlaanderen          BEL        Belgium      178.0       92.0   
1897                NaN          NaN        Ireland        NaN        NaN   
2115                NaN          NaN    Switzerland      176.0       67.0   
...                 ...          ...            ...        ...        ...   
143975              NaN          NaN         Zambia        NaN        NaN   
144172            Tirol          AUT        Austria        NaN        NaN   
144547       Syddanmark          DEN        Denmark        NaN        NaN   
144565      Hovedstaden          DEN        Denmark      186.0       93.0   
145435         Illinois          USA  United States        NaN        NaN   

         died_date  
6              NaN  
119     1967-11-05  
319            NaN  
1897           NaN  
2115           NaN  
...            ...  
143975         NaN  
144172         NaN  
144547         NaN  
144565         NaN  
145435  2023-06-12  

[303 rows x 10 columns]

## NOTES
#### Regex Comparison in str.contains()

#### These are the same (regex is default)
```python
str.contains('Keith|patrick', case=False)
str.contains('Keith|patrick', case=False, regex=True)
```

#### This is different (literal search)
```python
str.contains('Keith|patrick', case=False, regex=False)
# Would search for the exact string "Keith|patrick" including the | symbol
```

In [942]:
# "Find all players who were born in the USA, France, or Great Britain and whose name starts with 'Keith'."

players = bios[
    (bios['born_country'].isin(['USA', 'FRA', 'GBR'])) &
    (bios['name'].str.contains('Keith', na=False))
]
players.head(2)

athlete_id           name   born_date born_city born_region  \
3505         3517  Keith Wallace  1961-03-29   Preston     England   
12053       12118   Keith Hervey  1898-11-03    Fulham     England   

      born_country            NOC  height_cm  weight_kg   died_date  
3505           GBR  Great Britain      165.0       51.0  1999-12-31  
12053          GBR  Great Britain        NaN        NaN  1973-02-22

### ADDING OR REMOVING COLUMNS

In [943]:
# lets take coffee dataset here

# lets check all columns from dataset coffee

coffee.columns.to_list()

['Day', 'Coffee Type', 'Units Sold']

In [944]:
# Can you add a column name Price with value 4.99 ??


coffee['Price']=4.99  # this is how we add column
coffee.head(4)

Day Coffee Type  Units Sold  Price
0   Monday    Espresso          25   4.99
1   Monday       Latte          15   4.99
2  Tuesday    Espresso          30   4.99
3  Tuesday       Latte          20   4.99

In [945]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Day          14 non-null     object 
 1   Coffee Type  14 non-null     object 
 2   Units Sold   14 non-null     int64  
 3   Price        14 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 580.0+ bytes


In [946]:
#  Can you write "Write a Python statement using np.where to assign a new column,
#   new_price, in the DataFrame coffee, where the price is $3.99 for rows
#    where the Coffee Type is 'Espresso' and $5.99 otherwise."   ???

#    answer is >> np.where(condition, value_if_true, value_if_false)



# Solution 1 ---
coffee['New_Prices']=np.where(coffee['Coffee Type']=='Espresso',3.99,5.99)

coffee['New_Prices'].head(5)

0    3.99
1    5.99
2    3.99
3    5.99
4    3.99
Name: New_Prices, dtype: float64

#### Notes:

#### 🔹 What is `np.where()`?
`np.where()` is used to apply **conditional logic** to a column and assign values **vectorized (fast)**.

#### 🔹 Syntax
```python
np.where(condition, value_if_true, value_if_false)


In [947]:
# Lets check the dataframe coffee with New Column Name
coffee.head(4)

Day Coffee Type  Units Sold  Price  New_Prices
0   Monday    Espresso          25   4.99        3.99
1   Monday       Latte          15   4.99        5.99
2  Tuesday    Espresso          30   4.99        3.99
3  Tuesday       Latte          20   4.99        5.99

In [948]:
# below are alternative solution  for adding  columns

```markdown
## Solution 2: Using .loc[] with assignment

### Method 2A: Two-step assignment
```python
coffee['new_price'] = 5.99  # Default value for all
coffee.loc[coffee['Coffee Type'] == 'Espresso', 'new_price'] = 3.99
```

### Method 2B: One-step with .loc
```python
coffee.loc[:, 'new_price'] = 5.99
coffee.loc[coffee['Coffee Type'] == 'Espresso', 'new_price'] = 3.99
```

## Solution 3: Using .apply() with a function
```python
coffee['new_price'] = coffee['Coffee Type'].apply(
    lambda x: 3.99 if x == 'Espresso' else 5.99
)
```

## Solution 4: Using dictionary mapping
```python
price_map = {'Espresso': 3.99}
coffee['new_price'] = coffee['Coffee Type'].map(price_map).fillna(5.99)
```

## What each method does:

| Method | How it works | Best for |
|--------|-------------|----------|
| np.where() | Vectorized, fast | Simple if-else conditions |
| .loc[] | Direct assignment | When you need to update existing column |
| .apply() | Row-by-row function | Complex conditions/logic |
| .map() | Dictionary lookup | Many categories/values |
```

## Renaming of the columns

There are multiple ways to rename columns in pandas , I have made a seprate file which source path is below ,please check that out , Here I will be using most used method

"C:\Users\Nares\OneDrive\Google Drive DS cheat sheet\All Ways to Rename Columns in Pandas.pdf"

### Using .rename() Method to Rename Columns in Pandas

The `.rename()` method is the most flexible and commonly used way to rename columns in pandas. It allows you to rename specific columns or all columns using different approaches.

---

#### Method 1A: Rename Specific Columns with Dictionary

This approach uses a dictionary to map old column names to new ones. You can rename one or multiple columns at once.

```python
# Rename specific columns with inplace
df.rename(columns={'First Name': 'first_name', 'Last Name': 'last_name'}, inplace=True)
```

**Explanation:**
- `columns={'First Name': 'first_name', 'Last Name': 'last_name'}` - Dictionary where keys are old names and values are new names
- `inplace=True` - Modifies the original DataFrame directly (no need to reassign)
- Only the specified columns are renamed; other columns remain unchanged

```python
# Or without inplace
df = df.rename(columns={'First Name': 'first_name', 'Last Name': 'last_name'})
```

**Explanation:**
- Without `inplace=True`, the method returns a new DataFrame
- You must reassign it back to `df` (or another variable) to save the changes
- This is safer as it preserves the original DataFrame

---

#### Method 1B: Rename with a Function

Instead of a dictionary, you can pass a function that will be applied to each column name. This is useful when you want to transform all column names in the same way.

### Using Built-in Functions

```python
# Convert all to lowercase
df.rename(columns=str.lower, inplace=True)
```

**Explanation:**
- `str.lower` is a built-in Python function
- Applies `.lower()` to every column name
- Example: `'First Name'` becomes `'first name'`

---

#### Using Lambda Functions

```python
# Convert to snake_case
df.rename(columns=lambda x: x.lower().replace(' ', '_'), inplace=True)
```

**Explanation:**
- `lambda x:` - Creates an anonymous function where `x` is each column name
- `x.lower()` - Converts to lowercase
- `.replace(' ', '_')` - Replaces spaces with underscores
- Example: `'First Name'` becomes `'first_name'`

---

#### Using Custom Functions

```python
# Custom function
def clean_name(col):
    return col.strip().lower().replace(' ', '_')

df.rename(columns=clean_name, inplace=True)
```

**Explanation:**
- Define a reusable function with more complex logic
- `col.strip()` - Removes leading/trailing whitespace
- `.lower()` - Converts to lowercase
- `.replace(' ', '_')` - Replaces spaces with underscores
- Example: `' First Name '` becomes `'first_name'`
- This approach is better for complex transformations or when you need to reuse the logic

---

### Key Differences Summary

| Approach | Use When | Example |
|----------|----------|---------|
| **Dictionary** | Renaming specific columns only | Rename 'First Name' to 'first_name' |
| **Built-in function** | Simple transformation on all columns | Convert all to lowercase |
| **Lambda function** | One-line transformation on all columns | Replace spaces with underscores |
| **Custom function** | Complex multi-step transformation | Strip, lowercase, and replace |

---

## Important Notes

- **inplace=True**: Modifies the DataFrame directly (saves memory, but can't undo)
- **Without inplace**: Returns a new DataFrame (safer, but uses more memory)
- **Functions apply to ALL columns**: When using functions, they affect every column name
- **Dictionary only affects specified columns**: Other columns remain unchanged


In [949]:
# Removing of columns

# Question >> Can you remove the column Price from coffee dataset ?
# Question >> Can you add another column name revenue which is units sold * new_prices
# question << change the name of column new_price as updated price

In [950]:
coffee.head(2)

Day Coffee Type  Units Sold  Price  New_Prices
0  Monday    Espresso          25   4.99        3.99
1  Monday       Latte          15   4.99        5.99

In [951]:
# solution 1  removing column 'Price' permanently

coffee.drop(columns='Price', inplace=True)
coffee.head(2)

Day Coffee Type  Units Sold  New_Prices
0  Monday    Espresso          25        3.99
1  Monday       Latte          15        5.99

In [952]:
#Solution 2 adding another column name revenue

coffee['Revenue'] = coffee['Units Sold']* coffee['New_Prices']
coffee.head(3)

Day Coffee Type  Units Sold  New_Prices  Revenue
0   Monday    Espresso          25        3.99    99.75
1   Monday       Latte          15        5.99    89.85
2  Tuesday    Espresso          30        3.99   119.70

In [953]:
# Solution 3 changing the name of column new_price as updated price

coffee['Updated_Prices']=coffee['New_Prices']
coffee.drop(columns='New_Prices',inplace=True)
coffee.head(3)


# we could also used this one >>>  coffee.rename(columns={'new_price':'price'},inplace='True')

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0   Monday    Espresso          25    99.75            3.99
1   Monday       Latte          15    89.85            5.99
2  Tuesday    Espresso          30   119.70            3.99

In [954]:
# LETS CHECK ANOTHER DATASET >>
bios.head(3)

athlete_id                   name   born_date born_city  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux   
1           2         Arnaud Boetsch  1969-04-01    Meulan   
2           3           Jean Borotra  1898-08-13  Biarritz   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17

In [955]:
# Can you make a new df called bios_new and then find the first name for athelete


bios_new=bios.copy()
bios_new.head(3)

athlete_id                   name   born_date born_city  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux   
1           2         Arnaud Boetsch  1969-04-01    Meulan   
2           3           Jean Borotra  1898-08-13  Biarritz   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17

In [956]:
# find the first name for athelete
bios_new['first_name']= bios_new['name'].str.split(' ').str[0]
bios_new['first_name'].head(3)

0    Jean-François
1           Arnaud
2             Jean
Name: first_name, dtype: object

In [957]:
bios_new.head(3)

athlete_id                   name   born_date born_city  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux   
1           2         Arnaud Boetsch  1969-04-01    Meulan   
2           3           Jean Borotra  1898-08-13  Biarritz   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   

    died_date     first_name  
0  1960-10-02  Jean-François  
1         NaN         Arnaud  
2  1994-07-17           Jean

In [958]:
# find the last name for athelete
bios_new['last_name']= bios_new['name'].str.split(' ').str[1]
bios_new['last_name'].head(4)

0    Blanchy
1    Boetsch
2    Borotra
3    Brugnon
Name: last_name, dtype: object

In [959]:
bios_new.head(3)

athlete_id                   name   born_date born_city  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux   
1           2         Arnaud Boetsch  1969-04-01    Meulan   
2           3           Jean Borotra  1898-08-13  Biarritz   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   

    died_date     first_name last_name  
0  1960-10-02  Jean-François   Blanchy  
1         NaN         Arnaud   Boetsch  
2  1994-07-17           Jean   Borotra

In [960]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   athlete_id    145500 non-null  int64  
 1   name          145500 non-null  object 
 2   born_date     143693 non-null  object 
 3   born_city     110908 non-null  object 
 4   born_region   110908 non-null  object 
 5   born_country  110908 non-null  object 
 6   NOC           145499 non-null  object 
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object 
 10  first_name    145500 non-null  object 
 11  last_name     145500 non-null  object 
dtypes: float64(2), int64(1), object(9)
memory usage: 13.3+ MB


Here you see born_date is also an object which is categorical but remeber while working with dates always change it to date time

In [961]:
# can you make a new column where born_date is seen as  datetime  not like an object , also  handle invalid values


bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'], errors='coerce')
# This converts the born_datetime column to datetime format, and any invalid values (e.g., non-date strings) are set to NaT (Not a Time).

bios_new.head(3)

athlete_id                   name   born_date born_city  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux   
1           2         Arnaud Boetsch  1969-04-01    Meulan   
2           3           Jean Borotra  1898-08-13  Biarritz   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   

    died_date     first_name last_name born_datetime  
0  1960-10-02  Jean-François   Blanchy    1886-12-12  
1         NaN         Arnaud   Boetsch    1969-04-01  
2  1994-07-17           Jean   Borotra    1898-08-13

In [962]:
# lets check the data types again , and check the data type for this new column called born_datetime

bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype         
---  ------         --------------   -----         
 0   athlete_id     145500 non-null  int64         
 1   name           145500 non-null  object        
 2   born_date      143693 non-null  object        
 3   born_city      110908 non-null  object        
 4   born_region    110908 non-null  object        
 5   born_country   110908 non-null  object        
 6   NOC            145499 non-null  object        
 7   height_cm      106651 non-null  float64       
 8   weight_kg      102070 non-null  float64       
 9   died_date      33940 non-null   object        
 10  first_name     145500 non-null  object        
 11  last_name      145500 non-null  object        
 12  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(9)
memory usage: 14.4+ MB


 Perfect we have column born_datetime  and format is  143693 non-null  datetime64[ns]

In [963]:
# "How can I extract the birth year from a born_datetime column in a DataFrame and store it in a new column named born_year?"



bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new.head(4)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   

    died_date     first_name last_name born_datetime  born_year  
0  1960-10-02  Jean-François   Blanchy    1886-12-12     1886.0  
1         NaN         Arnaud   Boetsch    1969-04-01     1969.0  
2  1994-07-17           Jean   Borotra    1898-08-13     1898.0  
3  1978-03-20        Jacques   Brugnon    1895-05-11     1895.0

####  NOTE: born_year shows as 1886.0

- If `born_year` appears as `1886.0`, it means the column dtype is **float**.  
- This happens because **NaN (missing) values** exist in the dataset.  
- To fix it, convert the column to a **nullable integer type**.

```python
# Extract the year and convert to Nullable Integer type
bios_new['born_year'] = bios_new['born_datetime'].dt.year.astype('Int64')

# Preview the change
bios_new.head(4)


In [964]:
# # "What does extracting the year from a datetime column do in a dataset?"

bios_new.drop(columns=['born_year'],inplace=True) # dropped the previous float data type column and created it again

bios_new['born_year'] = bios_new['born_datetime'].dt.year.astype('Int64')
bios_new.head(2)

athlete_id                   name   born_date born_city born_region  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux     Gironde   
1           2         Arnaud Boetsch  1969-04-01    Meulan    Yvelines   

  born_country     NOC  height_cm  weight_kg   died_date     first_name  \
0          FRA  France        NaN        NaN  1960-10-02  Jean-François   
1          FRA  France      183.0       76.0         NaN         Arnaud   

  last_name born_datetime  born_year  
0   Blanchy    1886-12-12       1886  
1   Boetsch    1969-04-01       1969

#### Pandas Datetime Notes (Quick)

- `.dt` works **only** on datetime-like columns
- Column dtype must be `datetime64[ns]`
- Use `pd.to_datetime()` if dtype is `object` / string to convert into `datetime64[ns]`

####  Common `.dt` Accessors
- `.dt.year` → Year
- `.dt.month` → Month (1–12)
- `.dt.day` → Day of month
- `.dt.hour` → Hour
- `.dt.minute` → Minute
- `.dt.second` → Second
- `.dt.day_name()` → Day name (Monday, etc.)
- `.dt.month_name()` → Month name
- `.dt.weekday` → Day of week (Mon=0)
- `.dt.is_leap_year` → Leap year check

#### Correct Usage
```python
df['date'] = pd.to_datetime(df['date'])  # only if needed
df['date'].dt.year


In [965]:
# how will you check just three columns from the dataset like lets say print print athelete first name , last name and born year


bios_new[['first_name','last_name','born_year']].head(5)

first_name last_name  born_year
0  Jean-François   Blanchy       1886
1         Arnaud   Boetsch       1969
2           Jean   Borotra       1898
3        Jacques   Brugnon       1895
4         Albert     Canet       1878

In [966]:
bios_new.head(5)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   

    died_date     first_name last_name born_datetime  born_year  
0  1960-10-02  Jean-François   Blanchy    1886-12-12       1886  
1         NaN         Arnaud   Boetsch    1969-04-01       1969  
2  1994-07-17           Jean   Borotra    1898-08-13       1898  
3  1978-03-20        Jacques   Brugnon    1895-05-11       1895  
4  1930-07-25         Albert     Canet    1878-04-17       1878

## CREATING CATEGORIES IN A COLUMN
>> by using np.where


>> by creating a function


>> by using a lambda function

In [967]:
# Question >> # How will you  put athlete's height in category small(lets say <165 cm) , tall(>185) and average(165-185) ? Hint : Use np.where or lambda function


bios_new['Height_Category']=np.where(bios['height_cm']<170,'Short_Height',     # remember >> np.where(condition, value_if_true, value_if_false)
                             np.where(bios['height_cm']<185,'Average_Height','Tall_Height'))

bios_new.head(6)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   
5           6      Nicolas Chatelain  1970-01-13       Amiens   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   
5                 Somme          FRA  France      181.0       70.0   

    died_date     first_name  last_name born_datetime  born_year  \
0  1960-10-02  Jean-François    Blanchy    1886-12-12       1886   
1         NaN         Arnaud    Boetsch    1969-04-01       1969   
2  1994-07-17           Jean    Borotra    1898-08-13       1898   
3  1978-03-20        Jacques    Brugnon    1895-05-11       1895   
4  1930-07-25         Albert      Canet    1878-04-17       1878   
5         NaN        Nicolas  Chatelain    1970-01-13       1970   

  Height_Category  
0     Tall_Height  
1  Average_Height  
2  Average_Height  
3    Short_Height  
4     Tall_Height  
5  Average_Height

#### this code is bringiing NAN values under Tall_category which should be like Not Available , lets fix that in next cell

In [968]:

bios_new['Height_Category']=np.where(bios['height_cm']<=170,'Short_Height',     # remember >> np.where(condition, value_if_true, value_if_false)
                             np.where(bios['height_cm']<185,'Average_Height',
                              np.where(bios['height_cm']>=185,'Tall_Height','N/A')))

bios_new.head(6)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   
5           6      Nicolas Chatelain  1970-01-13       Amiens   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   
5                 Somme          FRA  France      181.0       70.0   

    died_date     first_name  last_name born_datetime  born_year  \
0  1960-10-02  Jean-François    Blanchy    1886-12-12       1886   
1         NaN         Arnaud    Boetsch    1969-04-01       1969   
2  1994-07-17           Jean    Borotra    1898-08-13       1898   
3  1978-03-20        Jacques    Brugnon    1895-05-11       1895   
4  1930-07-25         Albert      Canet    1878-04-17       1878   
5         NaN        Nicolas  Chatelain    1970-01-13       1970   

  Height_Category  
0             N/A  
1  Average_Height  
2  Average_Height  
3    Short_Height  
4             N/A  
5  Average_Height

In [969]:
# LEts check

bios_new[['height_cm','Height_Category']].head(5)

height_cm Height_Category
0        NaN             N/A
1      183.0  Average_Height
2      183.0  Average_Height
3      168.0    Short_Height
4        NaN             N/A

In [970]:
# # lets create another weight cotegories column  [LightWeight<=65, Heavy Weight>=90 , Middle_Weight<90 ]  from weight_kg column

# Function to categorize athletes by weight
def weight_category(athlete):
    if athlete['weight_kg'] <= 65:
        return 'LightWeight'
    elif athlete['weight_kg'] >= 90:
        return 'HeavyWeight'
    elif athlete['weight_kg'] < 90:
        return 'MiddleWieght'
    else:  # Anything in between
        return 'N/A'

# Apply the function to create a new column
bios_new['Weight_Category'] = bios_new.apply(weight_category, axis=1)

# Preview the result
bios_new[['weight_kg', 'Weight_Category']].head(6)

weight_kg Weight_Category
0        NaN             N/A
1       76.0    MiddleWieght
2       76.0    MiddleWieght
3       64.0     LightWeight
4        NaN             N/A
5       70.0    MiddleWieght

**💡 Note:** we could have used `np.where` as well, but I wanted to practice creating a function in such situations.  

Example using `np.where` to categorize weight:

```python
# Using np.where to categorize weight
bios_new['Weight_Category'] = np.where(
    bios_new['weight_kg'] <= 65, 'LightWeight',
    np.where(
        bios_new['weight_kg'] >= 90, 'HeavyWeight',
        'MiddleWeight'
    )
)


In [971]:
bios_new.head(5)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country     NOC  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   

    died_date     first_name last_name born_datetime  born_year  \
0  1960-10-02  Jean-François   Blanchy    1886-12-12       1886   
1         NaN         Arnaud   Boetsch    1969-04-01       1969   
2  1994-07-17           Jean   Borotra    1898-08-13       1898   
3  1978-03-20        Jacques   Brugnon    1895-05-11       1895   
4  1930-07-25         Albert     Canet    1878-04-17       1878   

  Height_Category Weight_Category  
0             N/A             N/A  
1  Average_Height    MiddleWieght  
2  Average_Height    MiddleWieght  
3    Short_Height     LightWeight  
4             N/A             N/A

In [972]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype         
---  ------           --------------   -----         
 0   athlete_id       145500 non-null  int64         
 1   name             145500 non-null  object        
 2   born_date        143693 non-null  object        
 3   born_city        110908 non-null  object        
 4   born_region      110908 non-null  object        
 5   born_country     110908 non-null  object        
 6   NOC              145499 non-null  object        
 7   height_cm        106651 non-null  float64       
 8   weight_kg        102070 non-null  float64       
 9   died_date        33940 non-null   object        
 10  first_name       145500 non-null  object        
 11  last_name        145500 non-null  object        
 12  born_datetime    143693 non-null  datetime64[ns]
 13  born_year        143693 non-null  Int64         
 14  Height_Category  145

In [973]:
# Let's save the new file
bios_new.to_csv('/content/drive/MyDrive/bios_new.csv', index=False)  # root folder , save confrimed !

 ### MERGING AND CONCATENATING DATA ---

In [974]:
# lets take the older dataset which is bios
bios.head(3)

athlete_id                   name   born_date born_city  \
0           1  Jean-François Blanchy  1886-12-12  Bordeaux   
1           2         Arnaud Boetsch  1969-04-01    Meulan   
2           3           Jean Borotra  1898-08-13  Biarritz   

            born_region born_country     NOC  height_cm  weight_kg   died_date  
0               Gironde          FRA  France        NaN        NaN  1960-10-02  
1              Yvelines          FRA  France      183.0       76.0         NaN  
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17

In [975]:
# lets take the another dataset which is noc

nocs=pd.read_csv('/content/drive/MyDrive/Python_Learning /Keith_Youtube_learning/Pandas_by_keith/noc_regions.csv')
nocs.head(5)

NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

SYNTAX FOR MERGING DATASETS USING LEFT JOIN >>>

```python
pd.merge(
    left_dataframe,
    right_dataframe,
    how='left',
    left_on='common_column_name',
    right_on='common_column_name'
)
```


In [976]:
# Question >> Can you change the born country name from 3 letters to full letter name
# For this we are going to use mergre both datasets using left  join

In [977]:
# Solutioin is mergring these two datasets using LEFT join

bios_merge = pd.merge(
    bios,                # remeber dont put them under comma as they are datasets not strings
    nocs,
    how='left',
    left_on='born_country',
    right_on='NOC'
)

bios_merge.head(5)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region born_country   NOC_x  height_cm  weight_kg  \
0               Gironde          FRA  France        NaN        NaN   
1              Yvelines          FRA  France      183.0       76.0   
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0   
3                 Paris          FRA  France      168.0       64.0   
4               England          GBR  France        NaN        NaN   

    died_date NOC_y  region notes  
0  1960-10-02   FRA  France   NaN  
1         NaN   FRA  France   NaN  
2  1994-07-17   FRA  France   NaN  
3  1978-03-20   FRA  France   NaN  
4  1930-07-25   GBR      UK   NaN

In [978]:
bios_merge.drop(columns=['born_country','NOC_x','NOC_y'],inplace=True)

bios_merge.head(5)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region  height_cm  weight_kg   died_date  region notes  
0               Gironde        NaN        NaN  1960-10-02  France   NaN  
1              Yvelines      183.0       76.0         NaN  France   NaN  
2  Pyrénées-Atlantiques      183.0       76.0  1994-07-17  France   NaN  
3                 Paris      168.0       64.0  1978-03-20  France   NaN  
4               England        NaN        NaN  1930-07-25      UK   NaN

In [979]:
# now lets rename column name from 'region' to 'born_country'

bios_merge.rename(columns={'region':'born_country'},inplace=True)
bios_merge.head(5)

athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux   
1           2         Arnaud Boetsch  1969-04-01       Meulan   
2           3           Jean Borotra  1898-08-13     Biarritz   
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe   
4           5           Albert Canet  1878-04-17   Wandsworth   

            born_region  height_cm  weight_kg   died_date born_country notes  
0               Gironde        NaN        NaN  1960-10-02       France   NaN  
1              Yvelines      183.0       76.0         NaN       France   NaN  
2  Pyrénées-Atlantiques      183.0       76.0  1994-07-17       France   NaN  
3                 Paris      168.0       64.0  1978-03-20       France   NaN  
4               England        NaN        NaN  1930-07-25           UK   NaN

In [980]:
# just wanted to check
bios_merge['born_country'].unique().tolist()

['France',
 'UK',
 nan,
 'Morocco',
 'Iraq',
 'USA',
 'South Africa',
 'Ireland',
 'India',
 'China',
 'Jamaica',
 'Australia',
 'Canada',
 'Germany',
 'Romania',
 'Brazil',
 'Czech Republic',
 'Russia',
 'Greece',
 'Egypt',
 'Hungary',
 'Poland',
 'Mexico',
 'Serbia',
 'Slovakia',
 'Indonesia',
 'Sri Lanka',
 'Pakistan',
 'Spain',
 'Austria',
 'Belgium',
 'Belarus',
 'Bulgaria',
 'Costa Rica',
 'Denmark',
 'Estonia',
 'Finland',
 'Switzerland',
 'Georgia',
 'Argentina',
 'Armenia',
 'Bahamas',
 'Cambodia',
 'Chile',
 'Israel',
 'Uzbekistan',
 'Italy',
 'Japan',
 'South Korea',
 'Latvia',
 'Ukraine',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malaysia',
 'Mauritius',
 'Netherlands',
 'Nigeria',
 'Norway',
 'Turkey',
 'New Zealand',
 'Paraguay',
 'Peru',
 'Barbados',
 'Guyana',
 'Republic of Congo',
 'Democratic Republic of the Congo',
 'Cameroon',
 'Colombia',
 'Puerto Rico',
 'Taiwan',
 'Vietnam',
 'Cuba',
 'Dominican Republic',
 'Croatia',
 'Ecuador',
 'El Salvador',
 'Moldova',
 

In [981]:
# Just wanted to check
bios_merge['born_country'].nunique()

201

In [982]:
# Can you make another datasets which has athelets only from USA ,
#                               and other datasets which has athlete from Britain only  ?

Athlete_USA= bios_merge[bios_merge['born_country']=='USA'].copy()

Athlete_USA.head(5)

athlete_id               name   born_date         born_city born_region  \
54            55      Monique Javer  1967-07-22        Burlingame  California   
960          964   Xóchitl Escobedo  1968-09-17       West Covina  California   
961          965  Angélica Gavaldón  1973-10-03         El Centro  California   
1231        1238     Bert Schneider  1897-07-01         Cleveland        Ohio   
1345        1352         Laura Berg  1975-01-06  Santa Fe Springs  California   

      height_cm  weight_kg   died_date born_country notes  
54        177.0       64.0         NaN          USA   NaN  
960       170.0       60.0         NaN          USA   NaN  
961       160.0       54.0         NaN          USA   NaN  
1231        NaN        NaN  1986-02-20          USA   NaN  
1345      168.0       61.0         NaN          USA   NaN

In [983]:
#2. datasets which has athlete from Britain only
Athlete_UK= bios_merge[bios_merge['born_country']=='UK'].copy()

Athlete_UK.head(5)

athlete_id               name   born_date    born_city born_region  \
4            5       Albert Canet  1878-04-17   Wandsworth     England   
37          38    Helen Aitchison  1881-12-06   Sunderland     England   
38          39  Geraldine Beamish  1883-06-23  Forest Gate     England   
39          40       Dora Boothby  1881-08-02     Finchley     England   
40          41     Julie Bradbury  1967-02-12       Oxford     England   

    height_cm  weight_kg   died_date born_country notes  
4         NaN        NaN  1930-07-25           UK   NaN  
37        NaN        NaN  1947-05-26           UK   NaN  
38        NaN        NaN  1972-05-10           UK   NaN  
39        NaN        NaN  1970-02-22           UK   NaN  
40      175.0       64.0         NaN           UK   NaN

#### HANDELING NULL VALUES


In [984]:
# Lets take the coffee dataset

coffee.info()

# for now it doesnt have any missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Day             14 non-null     object 
 1   Coffee Type     14 non-null     object 
 2   Units Sold      14 non-null     int64  
 3   Revenue         14 non-null     float64
 4   Updated_Prices  14 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 692.0+ bytes


In [985]:
# lets make another df coffee_nan

coffee_nan=coffee.copy()

coffee_nan

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0      Monday    Espresso          25    99.75            3.99
1      Monday       Latte          15    89.85            5.99
2     Tuesday    Espresso          30   119.70            3.99
3     Tuesday       Latte          20   119.80            5.99
4   Wednesday    Espresso          35   139.65            3.99
5   Wednesday       Latte          25   149.75            5.99
6    Thursday    Espresso          40   159.60            3.99
7    Thursday       Latte          30   179.70            5.99
8      Friday    Espresso          45   179.55            3.99
9      Friday       Latte          35   209.65            5.99
10   Saturday    Espresso          45   179.55            3.99
11   Saturday       Latte          35   209.65            5.99
12     Sunday    Espresso          45   179.55            3.99
13     Sunday       Latte          35   209.65            5.99

In [986]:
# lets add some null values in coffee_nan dataset

# coffee_nan['Units Sold']=np.nan    # this will make whole column as NaN
# coffee_nan.iloc[3,2]=np.nan        # if we want to chnage only one value


# I wanted to make every second values as NaN in Units Sold Column

for i in range(2,len(coffee_nan),3):       # range(2,len(coffee_nan),3) >> You can simplify range(2, len(coffee_nan), 3) to just range(2, 14, 3) since dataset has 14 rows (indices 0-13):
  coffee_nan.loc[i,'Units Sold']=np.nan


coffee_nan.head(15)

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0      Monday    Espresso        25.0    99.75            3.99
1      Monday       Latte        15.0    89.85            5.99
2     Tuesday    Espresso         NaN   119.70            3.99
3     Tuesday       Latte        20.0   119.80            5.99
4   Wednesday    Espresso        35.0   139.65            3.99
5   Wednesday       Latte         NaN   149.75            5.99
6    Thursday    Espresso        40.0   159.60            3.99
7    Thursday       Latte        30.0   179.70            5.99
8      Friday    Espresso         NaN   179.55            3.99
9      Friday       Latte        35.0   209.65            5.99
10   Saturday    Espresso        45.0   179.55            3.99
11   Saturday       Latte         NaN   209.65            5.99
12     Sunday    Espresso        45.0   179.55            3.99
13     Sunday       Latte        35.0   209.65            5.99

In [987]:
# Lets say you wanted to use iloc not loc
# import pandas as pd
# import numpy as np

# for i in range(2, len(coffee_nan), 3):     # Start at index 2, step by 3
#     coffee_nan.iloc[i, 2] = np.nan         # 2 is the column index for 'Units Sold'

# Check Missing values in a dataframe

In [988]:
coffee_nan.isna()

 #  will return a DataFrame of the same shape as coffee_nan,
 #   but with boolean values (True where there's a NaN, False where there isn't).

Day  Coffee Type  Units Sold  Revenue  Updated_Prices
0   False        False       False    False           False
1   False        False       False    False           False
2   False        False        True    False           False
3   False        False       False    False           False
4   False        False       False    False           False
5   False        False        True    False           False
6   False        False       False    False           False
7   False        False       False    False           False
8   False        False        True    False           False
9   False        False       False    False           False
10  False        False       False    False           False
11  False        False        True    False           False
12  False        False       False    False           False
13  False        False       False    False           False

In [989]:
# this is what we want to see (Total number of missing values per column)
coffee_nan.isna().sum()

Day               0
Coffee Type       0
Units Sold        4
Revenue           0
Updated_Prices    0
dtype: int64

>> Replacing Nan Values with Mean/mode/median - depeneds on situtaion

In [990]:
# we will be replacing Units Sold column's Nan Values with their Mean
coffee_nan['Units Sold']

0     25.0
1     15.0
2      NaN
3     20.0
4     35.0
5      NaN
6     40.0
7     30.0
8      NaN
9     35.0
10    45.0
11     NaN
12    45.0
13    35.0
Name: Units Sold, dtype: float64

In [991]:
mean_value=coffee_nan['Units Sold'].mean()
print(mean_value)

32.5


In [992]:
# Fill NaN values with the mean
coffee_nan['Units Sold'].fillna(mean_value, inplace=True)
coffee_nan['Units Sold']

0     25.0
1     15.0
2     32.5
3     20.0
4     35.0
5     32.5
6     40.0
7     30.0
8     32.5
9     35.0
10    45.0
11    32.5
12    45.0
13    35.0
Name: Units Sold, dtype: float64

# Dropping Missing Values in Pandas

## `dropna()` Overview
Removes rows or columns containing `NaN` values from a DataFrame. Flexible options based on your needs.

---

## Key Usage

### 1. `dropna(subset=['col'])`
- Drops rows with `NaN` in **specific column(s)** only
- `subset=['col1','col2']` for multiple columns
- Missing values in other columns are ignored

### 2. `dropna()`
- Drops rows with `NaN` in **any column**
- Default behavior; ensures complete data integrity

### 3. `inplace=True`
- Modifies the DataFrame **directly**
- `inplace=False` (default) returns a new DataFrame
- Saves memory with `inplace=True`

---

## Additional Parameters

- `axis=0` → drop rows (default), `axis=1` → drop columns  
- `how='any'` (default) → drop if any `NaN`, `how='all'` → drop only if all `NaN`  
- `thresh=n` → keep rows with at least `n` non-`NaN` values

---

## Best Practices
- Use `subset` for critical columns  
- Use plain `dropna()` for full completeness  
- Avoid `inplace=True` if original data is needed  
- Check rows affected: `df.isna().sum()`


In [993]:
 for i in range(2,len(coffee_nan),3):       # range(2,len(coffee_nan),3) >> You can simplify range(2, len(coffee_nan), 3) to just range(2, 14, 3) since dataset has 14 rows (indices 0-13):
  coffee_nan.loc[i,'Units Sold']=np.nan


coffee_nan.head(15)

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0      Monday    Espresso        25.0    99.75            3.99
1      Monday       Latte        15.0    89.85            5.99
2     Tuesday    Espresso         NaN   119.70            3.99
3     Tuesday       Latte        20.0   119.80            5.99
4   Wednesday    Espresso        35.0   139.65            3.99
5   Wednesday       Latte         NaN   149.75            5.99
6    Thursday    Espresso        40.0   159.60            3.99
7    Thursday       Latte        30.0   179.70            5.99
8      Friday    Espresso         NaN   179.55            3.99
9      Friday       Latte        35.0   209.65            5.99
10   Saturday    Espresso        45.0   179.55            3.99
11   Saturday       Latte         NaN   209.65            5.99
12     Sunday    Espresso        45.0   179.55            3.99
13     Sunday       Latte        35.0   209.65            5.99

In [994]:
# lets add Nan values again as we removed it above , then we will drop nan values using two ways


for i in range(2,len(coffee_nan),3):       # range(2,len(coffee_nan),3) >> You can simplify range(2, len(coffee_nan), 3) to just range(2, 14, 3) since dataset has 14 rows (indices 0-13):
  coffee_nan.loc[i,'Units Sold']=np.nan


coffee_nan.head(15)

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0      Monday    Espresso        25.0    99.75            3.99
1      Monday       Latte        15.0    89.85            5.99
2     Tuesday    Espresso         NaN   119.70            3.99
3     Tuesday       Latte        20.0   119.80            5.99
4   Wednesday    Espresso        35.0   139.65            3.99
5   Wednesday       Latte         NaN   149.75            5.99
6    Thursday    Espresso        40.0   159.60            3.99
7    Thursday       Latte        30.0   179.70            5.99
8      Friday    Espresso         NaN   179.55            3.99
9      Friday       Latte        35.0   209.65            5.99
10   Saturday    Espresso        45.0   179.55            3.99
11   Saturday       Latte         NaN   209.65            5.99
12     Sunday    Espresso        45.0   179.55            3.99
13     Sunday       Latte        35.0   209.65            5.99

In [995]:
coffee_nan.dropna() # it has removed the whole row which had nan values

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0      Monday    Espresso        25.0    99.75            3.99
1      Monday       Latte        15.0    89.85            5.99
3     Tuesday       Latte        20.0   119.80            5.99
4   Wednesday    Espresso        35.0   139.65            3.99
6    Thursday    Espresso        40.0   159.60            3.99
7    Thursday       Latte        30.0   179.70            5.99
9      Friday       Latte        35.0   209.65            5.99
10   Saturday    Espresso        45.0   179.55            3.99
12     Sunday    Espresso        45.0   179.55            3.99
13     Sunday       Latte        35.0   209.65            5.99

In [996]:
# lets check the data again , it will not change as we did not use inplace=True
coffee_nan.head(15)

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0      Monday    Espresso        25.0    99.75            3.99
1      Monday       Latte        15.0    89.85            5.99
2     Tuesday    Espresso         NaN   119.70            3.99
3     Tuesday       Latte        20.0   119.80            5.99
4   Wednesday    Espresso        35.0   139.65            3.99
5   Wednesday       Latte         NaN   149.75            5.99
6    Thursday    Espresso        40.0   159.60            3.99
7    Thursday       Latte        30.0   179.70            5.99
8      Friday    Espresso         NaN   179.55            3.99
9      Friday       Latte        35.0   209.65            5.99
10   Saturday    Espresso        45.0   179.55            3.99
11   Saturday       Latte         NaN   209.65            5.99
12     Sunday    Espresso        45.0   179.55            3.99
13     Sunday       Latte        35.0   209.65            5.99

In [997]:
#lets add some more nan values to the data again (Adding to Revenue Column)

for i in range(0,len(coffee_nan),2):
  coffee_nan.loc[i,'Revenue']=np.nan


coffee_nan.head(15)

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0      Monday    Espresso        25.0      NaN            3.99
1      Monday       Latte        15.0    89.85            5.99
2     Tuesday    Espresso         NaN      NaN            3.99
3     Tuesday       Latte        20.0   119.80            5.99
4   Wednesday    Espresso        35.0      NaN            3.99
5   Wednesday       Latte         NaN   149.75            5.99
6    Thursday    Espresso        40.0      NaN            3.99
7    Thursday       Latte        30.0   179.70            5.99
8      Friday    Espresso         NaN      NaN            3.99
9      Friday       Latte        35.0   209.65            5.99
10   Saturday    Espresso        45.0      NaN            3.99
11   Saturday       Latte         NaN   209.65            5.99
12     Sunday    Espresso        45.0      NaN            3.99
13     Sunday       Latte        35.0   209.65            5.99

In [1001]:
# adding one Nan  value to Updated Prices
coffee_nan.loc[9,'Updated_Prices'] = np.nan

coffee_nan.head(15)

Day Coffee Type  Units Sold  Revenue  Updated_Prices
0      Monday    Espresso        25.0      NaN            3.99
1      Monday       Latte        15.0    89.85            5.99
2     Tuesday    Espresso         NaN      NaN            3.99
3     Tuesday       Latte        20.0   119.80            5.99
4   Wednesday    Espresso        35.0      NaN            3.99
5   Wednesday       Latte         NaN   149.75            5.99
6    Thursday    Espresso        40.0      NaN            3.99
7    Thursday       Latte        30.0   179.70            5.99
8      Friday    Espresso         NaN      NaN            3.99
9      Friday       Latte        35.0   209.65             NaN
10   Saturday    Espresso        45.0      NaN            3.99
11   Saturday       Latte         NaN   209.65            5.99
12     Sunday    Espresso        45.0      NaN            3.99
13     Sunday       Latte        35.0   209.65            5.99

Now you see we have three columns with Nan values , Units Sold , Revenue has multiple Nan Values but Updated Prices has one Nan values , Now lets see the  difference in dropna() methods

In [1003]:
# # Lets use the other dropna() method

coffee_nan=coffee_nan.dropna(subset=['Units Sold','Revenue'])
coffee_nan.head(15)

Day Coffee Type  Units Sold  Revenue  Updated_Prices
1     Monday       Latte        15.0    89.85            5.99
3    Tuesday       Latte        20.0   119.80            5.99
7   Thursday       Latte        30.0   179.70            5.99
9     Friday       Latte        35.0   209.65             NaN
13    Sunday       Latte        35.0   209.65            5.99

So it will not remove Nan Values from the column Updated_Prices unless you mention it

In [1005]:
  coffee_nan=coffee_nan.dropna()
  coffee_nan.head(15)

Day Coffee Type  Units Sold  Revenue  Updated_Prices
1     Monday       Latte        15.0    89.85            5.99
3    Tuesday       Latte        20.0   119.80            5.99
7   Thursday       Latte        30.0   179.70            5.99
13    Sunday       Latte        35.0   209.65            5.99

And here dropna() has removed nan from everywhere , it does not require column names

## AGGREGATING DATA